version: "3.8"
services:
  web:
    image: nginx:1.18-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  echo-server:
    image: broadcast-echo-server
    build: ./infra/echoserver
    ports:
      - "6001:6001"
    command: laravel-echo-server start
    volumes:
      - ./backend:/work:cached
    working_dir: /work

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./infra/redis/data:/data

  mysql:
    build: ./infra/mysql
    ports:
      - "3306:3306"
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
